SELECT E3.ID
FROM ECOLI_DATA as E3   
    JOIN ECOLI_DATA as E2 ON E3.PARENT_ID = E2.ID
    JOIN (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
) as E1 ON E1.ID = E2.PARENT_ID
ORDER BY E3.ID ASC