SELECT CONCAT(T.quarter, 'Q') AS QUARTER, COUNT(T.ID) AS ECOLI_COUNT
FROM (
    SELECT QUARTER(DIFFERENTIATION_DATE) AS quarter, ID
    FROM ECOLI_DATA
) AS T
GROUP BY T.quarter
ORDER BY T.quarter ASC;
